//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiris
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnProduct
    {
        public int ReturnProductsID { get; set; }
        public int SalesID { get; set; }
        public decimal ReturnPrice { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
