//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiris
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.ReturnProducts = new HashSet<ReturnProduct>();
        }
    
        public int SalesID { get; set; }
        public int ProductID { get; set; }
        public int EmployeesID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ReturnProduct> ReturnProducts { get; set; }
    }
}
